\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={作業1},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{作業1}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
請依狀況更改上面的name,id及group（分別代表組員姓名，學號及組號），但請勿更改下面三行的設定。

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

姓名：林奕翔, 張鈞硯, 賴彥融, 吳宥履, 王童緯\\
學號：710761132, 710761104, 710761101, 710761118, 710761115\\
組號：team b\\
網頁：

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

作業除了讓同學檢視課堂所學程式外，有些題目只會給你未教過的函數建議（純為建議，你也可以不使用），你必需使用Help或網路查尋去了解函數的正確使用；搜詢正確程式函數使用的能力，也是程式設計的基本功。

如果是程式答案，在r chunk區塊裡面作答, 如：

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#你的程式答案}
\end{Highlighting}
\end{Shaded}

如果是文字答案，請直接在該題空白處回答。

\section{1 擋修的效果}

本校經濟系的\textbf{個體經濟學}與\textbf{總體經濟學}有擋修限制：

\begin{itemize}
\item
  可修習個經條件：需經原上學期及格，微積分上學期有修習且不為0分。
\item
  可修習總經條件：需經原上學期\textbf{不死當}（\textgreater{}=40分）且下學期及格。
\end{itemize}

擋修制度的用意在於讓學生於先修課程達一定基礎後，才有能力學好後面的進階課程。

\subsection{1.1 效應評估}

我們以個體經濟學為考量之進階課程，學生學習成效以\textbf{個經PR}（即學生第一次第一學期修完個經在同班的排名）來衡量。令\textbf{可修個體}虛擬變數其值為1若該學生通過修課限制可以修個經，反之為0。請寫下正確的效應結構（
課堂上的Y即這裡的
\textbf{個經PR}，請對應課堂的\(Y_{1i}-Y_{0i}\)寫法，寫出這題的表示句子。)

\[PR_{1k}-PR_{0k}\]
\(PR_{1k}\)為未被擋修學生的排名，\(PR_{0k}\)為被擋修學生的排名。
在兩個變數中，都有一個情境的薪資是觀察不到的。令PR為可以觀察到的成績（可能是沒被擋修的成績\(PR_{1k}\),也可能是沒被擋修的成績\(PR_{0k}\)，視對象實際有無被擋修而定）。

\subsection{1.2 效應結構}

接續上題，課堂上的treatment
dummy即為這裡的\textbf{可修個體}dummy，請寫下對應課堂效應結構\(Y_i=Y_{0i}+(Y_{1i}-Y_{0i})T_i\)之對應寫法（以這裡的文字符號表示）。

\[PR_{k}=PR_{0k}+(PR_{1k}-PR_{0k}) T_{k}\]
k泛指任何人，上式表示每一個沒有被的擋修的人（即T=1)，他的實際成績是他的「被擋修的成績」再加上「沒有被擋修的效果」所造成。

令\(\delta_{k}=PR_{1k}-PR_{0k}\)代表每個人有沒有被擋修的成績效果，假設每個人沒有被擋修的效果相同\(\delta_{k}=\delta\)則：
\[PR_{k}=PR_{0k}-\delta T_{k}\]

\subsection{1.3 簡單迴歸模型}

考慮使用如下的簡單迴歸模型來估計效應係數：
\[個經PR_i=\beta_0+\beta_1 可修個體_i+\epsilon_i\]

執行以下程式引入作業資料\textbf{hw1Data}:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(readr)}
\NormalTok{hw1Data <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/tpemartin/github-data/master/econometrics107-2-hw1.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

其中變數定義如下：

\begin{itemize}
\item
  \textbf{個經學年期}：個經PR來自的學年-學期，100-2即來自100年第2學期。
\item
  \textbf{個經PR}：學生\textbf{第一次}修習個經於該班上的個經成績排名，PR為勝過的人數比例。
\item
  \textbf{可修個體}：「學生在大一結束後有達到可修個經門檻」其值為1的dummy
  variable。
\end{itemize}

請進行OLS估計前述的簡單迴歸模型。（注意估計式標準誤必需使用穩健標準誤robust
standard error，即使用三明治及HC調整後的標準誤。）

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hw1Data }\OperatorTok{$}\NormalTok{個經PR ->}\StringTok{ }\NormalTok{mipr}
\NormalTok{hw1Data }\OperatorTok{$}\NormalTok{可修個體 ->}\StringTok{ }\NormalTok{ami}

\KeywordTok{lm}\NormalTok{(mipr}\OperatorTok{~}\NormalTok{ami) ->}\StringTok{ }\NormalTok{model_}\DecValTok{1}
\KeywordTok{library}\NormalTok{(lmtest)}
\KeywordTok{library}\NormalTok{(sandwich)}
\KeywordTok{coeftest}\NormalTok{(model_}\DecValTok{1}\NormalTok{, }\DataTypeTok{vcov. =}\NormalTok{ vcovHC, }\DataTypeTok{type=}\StringTok{"HC1"}\NormalTok{) ->}\StringTok{ }\NormalTok{model_1_coeftest}
\NormalTok{model_1_coeftest}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## t test of coefficients:
## 
##             Estimate Std. Error t value  Pr(>|t|)    
## (Intercept) 0.285110   0.025739 11.0768 < 2.2e-16 ***
## ami         0.078732   0.028788  2.7349  0.006407 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\(\beta_{0}=0.285110\)，\(\beta_{1}=0.078732\)，且由p-value=0.0064知道個經成績可被有沒有被擋修解釋，沒被擋修的同學的個經PR會比被擋修的同學高出0.079。

\subsection{1.4 選擇性偏誤}

上題的估計結果很可能不正確，請說明原因故事（非數學證明）。

因為立足點高的人（即經原成績較高）個經成績也傾向較高，所以單純比較每被擋修與有被擋修的個經成績，除了反應有沒有被擋修的效果之外，也反應了立足點的差異。

\subsection{1.5 選擇性偏誤}\label{-1}

這個資料還包含\textbf{經原PR}變數，它是學生最後修過的經原成績在該經原班的排名。說明有必要控制\textbf{經原PR}的理由（非數學證明）。

經原成績可用來代表學生一開始的程度高低，經原成績好的同學亦可能在個經表現優異，因此須將經原成績列入考量，才可能將不同能力的同學放在同樣的立足點比較。

\subsection{1.6 複迴歸模型}

估算以下的複迴歸模型：
\[個經PR_i=\beta_0+\beta_1 可修個體_i+經原PR_i+\epsilon_i.\]
（注意估計式標準誤必需使用穩健標準誤robust standard
error，即使用三明治及HC調整後的標準誤。）

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hw1Data }\OperatorTok{$}\NormalTok{經原PR ->}\StringTok{ }\NormalTok{ecopr}

\KeywordTok{lm}\NormalTok{(mipr}\OperatorTok{~}\NormalTok{ami}\OperatorTok{+}\NormalTok{ecopr) ->}\StringTok{ }\NormalTok{model_}\DecValTok{2}
\KeywordTok{coeftest}\NormalTok{(model_}\DecValTok{2}\NormalTok{, }\DataTypeTok{vcov. =}\NormalTok{ vcovHC, }\DataTypeTok{type=}\StringTok{"HC1"}\NormalTok{) ->}\StringTok{ }\NormalTok{model_2_coeftest}
\NormalTok{model_2_coeftest}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## t test of coefficients:
## 
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 0.252055   0.028751  8.7670  < 2e-16 ***
## ami         0.068024   0.028978  2.3475  0.01920 *  
## ecopr       0.096260   0.038603  2.4936  0.01289 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

由此可知，\(\beta_{0}=0.252055\)，\(\beta_{1}=0.068024\)，\(\beta_{2}=0.096260\)。

\subsection{1.7 變數關連}

請計算\textbf{可修個體}為1與0兩群人的\textbf{經原PR平均}及\textbf{個經PR平均}。（hint:
可利用dplyr套件下的\texttt{group\_by()},\texttt{summarise()}，及\texttt{mean(\ ,na.rm=T)},
na.rm=T表示計算時排除NA值）

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hw1Data }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(可修個體) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(經原}\DataTypeTok{avg =} \KeywordTok{mean}\NormalTok{(經原PR,}\DataTypeTok{na.rm=}\NormalTok{T),個經}\DataTypeTok{avg =} \KeywordTok{mean}\NormalTok{(個經PR,}\DataTypeTok{na.rm=}\NormalTok{T))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   可修個體 經原avg 個經avg
##      <dbl>   <dbl>   <dbl>
## 1        0   0.320   0.285
## 2        1   0.383   0.364
\end{verbatim}

\subsection{1.8 偏誤方向}

請填入以下空格完成完整偏誤論述：\\
有控制\textbf{經原PR}時，擋修會使得\textbf{個經PR}
(1)\textbf{下降}(上升/下降)
(2)\_\_6.8024\_\_百分點，其值比未控制\textbf{經原PR}時還
(3)\textbf{低}(高/低)；這表示忽略\textbf{經原PR}會對效應係數估計產生
(4)\textbf{正向偏誤}(正向偏誤(upward bias)/負向偏誤(downward
bias))。之所以會有上述的偏誤方向來自於兩個因素：

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{經原PR}與\textbf{個經PR}有(5)\textbf{正向}(正向/反向)關連
\item
  \textbf{可修個體}=1的族群，其\textbf{經原PR}平均較(6)\textbf{高}(高/低)
\end{enumerate}

故若不控制\textbf{經原PR}，因\textbf{可修個體}=1與=0兩群人也會分別帶有
\textbf{經原PR}
(7)\textbf{高與低}(高與低/低與高)特質，所以\textbf{可修個體}=1的人其\textbf{個經PR}高，有部份是因其\textbf{經原PR}也較(8)\textbf{高}(高/低)所至。

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(stargazer)}

\KeywordTok{stargazer}\NormalTok{(model_}\DecValTok{1}\NormalTok{, model_}\DecValTok{2}\NormalTok{, }
          \DataTypeTok{se=}\KeywordTok{list}\NormalTok{(model_1_coeftest[,}\StringTok{"Std. Error"}\NormalTok{], model_2_coeftest[,}\DecValTok{2}\NormalTok{]),}
          \DataTypeTok{type=}\StringTok{"html"}\NormalTok{,}
          \DataTypeTok{align=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Dependent variable:

mipr

(1)

(2)

ami

0.079***

0.068**

(0.029)

(0.029)

ecopr

0.096**

(0.039)

Constant

0.285***

0.252***

(0.026)

(0.029)

Observations

665

665

R2

0.005

0.014

Adjusted R2

0.004

0.011

Residual Std. Error

0.309 (df = 663)

0.308 (df = 662)

F Statistic

3.377* (df = 1; 663)

4.583** (df = 2; 662)

Note:

\emph{p\textless{}0.1; \textbf{p\textless{}0.05; }}p\textless{}0.01

\subsection{1.9 (Optional, 可不寫)}\label{optional-}

從前面的論述你發現什麼？背後的效應反映出什麼課程結構或學生學習問題？你會怎麼延伸研究下去。

曾被擋修的學生之個經PR值平均仍然低於沒被擋修過的學生PR值平均，顯示即使跨過擋修門檻後再去修個經，成績也不太會有所提升，因此擋修這個制度對學生的學習效果並沒有太大的幫助，成績的差異來源並不是是否修過經原，而是來自學生自身的能力和家庭背景及花在該門課程上的時間，因此若要延伸研究，我們會想以家庭所得和讀書時間做為解釋變數，去試著解釋不同學生在個經成績上的差異。

\section{2 理論}

\subsection{2.1}\label{section}

考慮如下的迴歸模型：

\[y_i=\beta_0+\beta_1x_i+\epsilon_i,\] 若使用最小平方法估計，則
\[\hat{\beta}_1=\frac{\sum_{i=1}^N (x_i-\bar{x})(y_i-\bar{y})}{\sum_{i=1}^N (x_i-\bar{x})^2}\]

其中\(x_i\)為0或1的虛擬變數，且令\(n_0\)與\(n_1\)分別為樣本中\(x_i=0\)與\(x_i=1\)的個數。

請證明： \[\hat{\beta}_1=\bar{y}_1-\bar{y}_0,\]
其中\(\bar{y}_1=\sum_{i,x_i=1}y_i/n_1\)與\(\bar{y}_0=\sum_{i,x_i=0}y_i/n_0\)分別為\(x_i=1\)與\(x_i=0\)兩群樣本的\(y_i\)平均。

提示：證明過程可以適時的使用以下特質：

\begin{itemize}
\item
  \[\sum_i w_i=\sum_{i,x_i=1} w_i +\sum_{i,x_i=0} w_i\]
\item
  \(\bar{x}=n_1/n\), 其中\(n=n_0+n_1\)。
\end{itemize}

~

\begin{align}
\hat{\beta}_1
&=\frac{\sum_{i=1}^N (x_i-\bar{x})(y_i-\bar{y})}{\sum_{i=1}^N (x_i-\bar{x})^2}=\frac{\sum_{i,x_i=1}^N (1-\frac{n_1}{n})(y_i-\bar{y})+\sum_{i,x_i=0}^N (0-\frac{n_1}{n})(y_i-\bar{y})}{\sum_{i,x_i=1}^N (1-\frac{n_1}{n})^2+\sum_{i,x_i=0}^N (0-\frac{n_1}{n})^2}\\
\\
&=\frac{(\frac{n_0}{n})\sum_{i,x_i=1}^N(y_i-\bar{y})+(\frac{n_1}{n})\sum_{i,x_i=0}^N(y_i-\bar{y})}{n_1(\frac{n_0}{n})^2+n_0(\frac{n_1}{n})^2}=\frac{(\frac{n_0}{n})\sum_{i,x_i=1}^N y_i-(\frac{n_1}{n})\sum_{i,x_i=0}^N y_i}{\frac{n_1 n_0^2+n_0 n_1^2}{n^2}}\\
\\
&=\frac{(\frac{\sum_{i,x_i=1}^N y_i}{n_1})-(\frac{\sum_{i,x_i=0}^N y_i}{n_0})}{\frac{n_0+ n_1}{n}}=\bar{y_1}-\bar{y_0}
\end{align}

\subsection{2.2}\label{section-1}

假設\(E(\epsilon_i|x_i)=0\)，證明上題設定下：

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  \(E(\hat{\beta}_1)=\beta_1\)
\item
  若條件在已知已知每個觀測值的\(x_i\)為1或0下\(V(\epsilon_i|x_i)=\sigma^2\)（即齊質變異），則條件變異數\(V(\hat{\beta}_1|X)=\frac{n}{n_1 n_0}\sigma^2\)。
\item
  若考慮異質變異\(V(\epsilon_i|x_i=0)=\sigma_0^2\)、\(V(\epsilon_i|x_i=1)=\sigma_1^2\)，則條件變異數\(V(\hat{\beta}_1|X)=\frac{\sigma_0^2}{n_0}+\frac{\sigma_1^2}{n_1}\)。
\end{enumerate}

\begin{align}
(a)\,\,\,\,\,\,E(\hat{\beta_1})&=E(\bar{y_1}-\bar{y_0})=E(\bar{y_1})-E(\bar{y_0})=E(\frac{\sum_{i,x_i=1}^Ny_i}{n_1})-E(\frac{\sum_{i,x_i=0}^Ny_i}{n_0})\\
\\
&=(\frac{1}{n_1})\sum_{i,x_i=1}^N E(y_1)-(\frac{1}{n_0})\sum_{i,x_i=0}^N E(y_0)=(\beta_0+\beta_1)-\beta_0=\beta_1\\
\\
(b)\,\,V(\hat{\beta_1}|x)&=V(\bar{y_1}-\bar{y_0}|x)=V(\bar{y_1})+V(\bar{y_0})-2cov(\bar{y_1},\bar{y_0}),\,cov(\bar{y_1},\bar{y_0})=0 \\
\\
&=(\frac{1}{n_1^2})n_1\sigma^2+(\frac{1}{n_0^2})n_0\sigma^2=\frac{n}{n_1n_0}\sigma^2\\
\\
(c)\,\,V(\hat{\beta_1}|x)&=V(\bar{y_1}-\bar{y_0}|x)=V(\bar{y_1})+V(\bar{y_2})-2cov(\bar{y_1},\bar{y_2})\\
\\
&=\frac{\sigma_1^2}{n_1}+\frac{\sigma_0^2}{n_0}
\end{align}

\subsection{2.3 三明治表示式}

線性迴歸模型 \(Y=X\beta+\epsilon\)
的OLS估計式\(\hat{\beta}=(X'X)^{-1}(X'Y)\)。條件在已知\(X\)下，令\(V(\epsilon|X)=\Sigma\)。請證明\(V(\hat{\beta}|X)=(X'X)^{-1}X'\Sigma X (X'X)\)，具有三明治形式（即可表示成\(BMB'\)的矩陣相乘形式）。

~

\begin{align}
Var(\epsilon)&=E(\epsilon\epsilon')=\sigma^2I_n=\sum\\
\\
Var(\hat{\beta})&=E\{[\hat{\beta}-E(\hat{\beta})][\hat{\beta}-E(\hat{\beta})]\}=(x'x)^{-1}x'E(\epsilon\epsilon')x(x'x)^{-1}\\
\\
&=(x'x)^{-1}x'\sum\,x(x'x)^{-1}
\end{align}


\end{document}
